### ISSUE TITLE
Tighten lower bounds

### ISSUE THREAD

**Issue by kvanbere** [cuedo/github-webhooks#7]
The lower bounds on all of the versions are absent which may cause issues for people using cabal without a resolver like `stack` or `nix`. Add at least a set of lenient lower bounds and perhaps support older GHC as per #6 .

**Comment by christiansakai** [comment]
@donkeybonks 

What's the best way to do this? Does this mean I need to install global GHC and check the lowest bound?

**Comment by donkeybonks** [comment]
@christiansakai Yes, this requires building without stack -- perhaps using cabal sandbox and a global GHC from apt or such. Would need to use the oldest supported version of GHC, which is tentatively GHC 7.4 although that may change depending on outcome of #6.

**Comment by kvanbere** [comment]
I don't think is required anymore, as we've tested compiling with resolvers all the way back to `ghc-7.8`.
